import nextEslintConfig from "eslint-config-next";

/** Native flat config from `eslint-config-next` (avoid FlatCompat + circular config in ESLint 9). */
const eslintConfig = [
  {
    // Generated by `withEve()` / the dev server, and gitignored. Linting the
    // bundled output reports errors in vendored code, so `bun run lint` fails
    // on any machine that has run `bun dev`.
    ignores: [".eve/**", ".output/**", ".next/**"],
  },
  ...nextEslintConfig,
  {
    // ReUI is vendored component-library code whose imperative table/virtualizer
    // integrations are intentionally outside React Compiler's supported subset.
    files: ["components/reui/**/*.{ts,tsx}"],
    rules: {
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/use-memo": "off",
    },
  },
];

export default eslintConfig;
