#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ENV_FILE:-scripts/.cutover-invoicey-app.state}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRAND="$ROOT/apps/web/public/brand/external"
VERCEL_SCOPE="ditrich"
VERCEL_PROJECT="inveoiceyai-web"

set_vercel_prod_env() {
  local key="$1" value="$2"
  if ! command -v vercel >/dev/null 2>&1; then
    SKIPPED+=("Vercel env $key (vercel CLI missing)")
    warn "vercel CLI missing; set $key= $value on Production yourself"
    return
  fi
  if vercel env add "$key" production \
    --value "$value" \
    --force \
    --yes \
    --no-sensitive \
    --scope "$VERCEL_SCOPE" \
    --project "$VERCEL_PROJECT" \
    --cwd "$ROOT" >/dev/null; then
    printf '  %s✓ set%s Vercel Production %s\n' "$GREEN" "$RESET" "$key"
  else
    SKIPPED+=("Vercel env $key")
    warn "could not set Vercel Production $key; set it in the dashboard"
  fi
}

TOTAL_STAGES=11

banner "Invoicey.app cutover + provider brand"

# ── 1. DNS / cert ─────────────────────────────────────────────────────────
stage "Apex DNS and certificate"
say "invoicey.app is already on Vercel DNS and attached to inveoiceyai-web."
say "www.invoicey.app is attached too. .app is HSTS-preloaded — wait for HTTPS."
open_url "https://vercel.com/ditrich/inveoiceyai-web/settings/domains"
step "Confirm both invoicey.app and www.invoicey.app are listed on this project."
step "On www.invoicey.app, set Redirect to https://invoicey.app (apex)."
step "Do not remove invoicey.ditrich.me. Machine clients still need it."
pause "Domains look right? Press Enter to probe HTTPS."
until curl -fsSI --max-time 15 https://invoicey.app >/dev/null 2>&1; do
  warn "https://invoicey.app is not answering yet (DNS or cert still propagating)."
  pause "Press Enter to retry the probe"
done
printf '  %s✓%s https://invoicey.app answers\n' "$GREEN" "$RESET"
write_env APEX_HTTPS_OK 1

# ── 2. Google OAuth callbacks ─────────────────────────────────────────────
stage "Google OAuth: add the new origin"
say "Add the new callbacks BEFORE we flip BETTER_AUTH_URL. Keep the old ones."
open_url "https://console.cloud.google.com/auth/clients"
step "Open the production Invoicey Web client (the one in Vercel GOOGLE_CLIENT_ID)."
step "Authorized JavaScript origins — Add URI: https://invoicey.app"
step "Authorized redirect URIs — Add URI: https://invoicey.app/api/auth/callback/google"
step "Leave the existing invoicey.ditrich.me origin and redirect in place."
step "Save."
pause "Google client saved with both hosts?"
write_env GOOGLE_CALLBACKS_OK 1

# ── 3. Google OAuth branding ──────────────────────────────────────────────
stage "Google OAuth: brand + legal URLs"
say "Consent-screen logo and homepage must match the new host."
open_url "file://${BRAND}/invoicey-google-oauth-120.png"
open_url "https://console.cloud.google.com/auth/branding"
step "Application name stays Invoicey."
step "Application logo: upload the 120×120 PNG that just opened (under 1 MB)."
step "Homepage: https://invoicey.app"
step "Privacy policy: https://invoicey.app/privacy"
step "Terms: https://invoicey.app/terms"
step "Save. If Google opens a new brand-verification draft, publish it."
warn "A logo change can create a draft that users will not see until you publish."
pause "Google branding saved (and published if it asked)?"
write_env GOOGLE_BRAND_OK 1

# ── 4. GitHub OAuth ───────────────────────────────────────────────────────
stage "GitHub OAuth: callback, homepage, logo"
say "This is the OAuth App under Developer settings — not the repo homepage."
open_url "file://${BRAND}/invoicey-github-oauth-200.png"
open_url "https://github.com/settings/developers"
step "Open the production Invoicey OAuth App."
step "Homepage URL: https://invoicey.app"
step "Authorization callback URL: https://invoicey.app/api/auth/callback/github"
step "If the UI only allows one callback, put the new one. The old host will 308 HTML later."
step "Application logo: upload the 200×200 PNG that opened. Badge background #0b0b0c."
step "Update description if it still mentions ditrich.me. Save."
pause "GitHub OAuth app saved?"
write_env GITHUB_OAUTH_OK 1

# ── 5. Resend domain ──────────────────────────────────────────────────────
stage "Resend: verify invoicey.app"
say "DNS is on Vercel, so add Resend's records there — not at a registrar."
open_url "https://resend.com/domains"
step "Add Domain → invoicey.app (not www, not a subdomain)."
step "Copy every record Resend shows (TXT verify, DKIM, SPF)."
open_url "https://vercel.com/ditrich/inveoiceyai-web/settings/domains"
step "Open invoicey.app → DNS (or Vercel team Domains → invoicey.app → Records)."
step "Add each Resend record exactly. Do not delete the existing ALIAS/CAA rows."
step "Back in Resend, click Verify. Wait until the domain is Verified."
step "Keep invoicey.ditrich.me verified. Do not delete it."
pause "Resend shows invoicey.app as Verified?"
write_env RESEND_DOMAIN_OK 1
if confirm "Update local .env From addresses to @invoicey.app now?"; then
  _cutover_state="$ENV_FILE"
  ENV_FILE="$ROOT/.env"
  write_env EMAIL_FROM "Invoicey <invoices@invoicey.app>"
  write_env EMAIL_SYSTEM_FROM "Invoicey <noreply@invoicey.app>"
  ENV_FILE="$_cutover_state"
fi

# ── 6. Resend webhook ─────────────────────────────────────────────────────
stage "Resend: delivery webhook"
say "The route is the same function. Point it at the new host (or keep both)."
open_url "https://resend.com/webhooks"
step "Open the existing delivery-events webhook (email.sent / delivered / bounced / …)."
step "Endpoint URL → https://invoicey.app/api/webhooks/resend"
step "If the UI is create-only, add a second webhook to that URL with the same events."
step "Do not rotate RESEND_WEBHOOK_SECRET unless Resend issued a new one."
note "Leave the inbound email.received webhook alone if it still exists — inbound was removed."
pause "Webhook URL saved?"
write_env RESEND_WEBHOOK_OK 1

# ── 7. Slack brand ────────────────────────────────────────────────────────
stage "Slack app: icon, name, website"
say "Display only. Do not detach Vercel Connect. Trigger path stays /eve/v1/slack."
open_url "file://${BRAND}/invoicey-slack-512.png"
open_url "https://api.slack.com/apps"
step "Open the Slack app attached to Vercel Connect slack/invoicey."
step "Basic Information → Display Information."
step "App name: Invoicey. Upload the 512×512 PNG that opened (full-bleed, no extra rounding)."
step "Short description if it still mentions ditrich.me."
step "App website / Help / Privacy / Terms if those fields exist:"
step "  https://invoicey.app   https://invoicey.app/privacy   https://invoicey.app/terms"
step "Save Changes. Skip a reinstall unless Slack says URLs or scopes changed."
pause "Slack display saved?"
write_env SLACK_BRAND_OK 1

# ── 8. Search Console ─────────────────────────────────────────────────────
stage "Google Search Console"
say "New host needs its own property. Keep the old ditrich.me property."
open_url "https://search.google.com/search-console"
step "Add property → URL prefix → https://invoicey.app/"
step "Choose the HTML-file or meta-tag method, or use the Vercel domain already on this Google account."
step "After ownership is verified, sitemaps → add https://invoicey.app/sitemap.xml"
pause "Property added (or skipped if you will do it later)?"
write_env SEARCH_CONSOLE_OK 1

# ── 9. Flip production env ────────────────────────────────────────────────
stage "Flip Vercel Production env"
warn "Do this only after Google + GitHub callbacks exist. The next deploy will use them."
say "This overwrites Production (not Preview) NEXT_PUBLIC_APP_URL, BETTER_AUTH_URL,"
say "EMAIL_FROM, and EMAIL_SYSTEM_FROM. Local .env stays localhost."
if confirm "Write the four Production env vars now?"; then
  set_vercel_prod_env NEXT_PUBLIC_APP_URL "https://invoicey.app"
  set_vercel_prod_env BETTER_AUTH_URL "https://invoicey.app"
  set_vercel_prod_env EMAIL_FROM "Invoicey <invoices@invoicey.app>"
  set_vercel_prod_env EMAIL_SYSTEM_FROM "Invoicey <noreply@invoicey.app>"
  write_env VERCEL_ENV_FLIPPED 1
else
  SKIPPED+=("Vercel Production env flip")
  warn "skipped env flip; run this stage again after OAuth is ready"
fi

# ── 10. Redeploy ──────────────────────────────────────────────────────────
stage "Redeploy production"
say "Env changes do not hit the current deployment. NEXT_PUBLIC_* needs a rebuild."
open_url "https://vercel.com/ditrich/inveoiceyai-web/deployments"
step "Open the current Production deployment → ⋯ → Redeploy."
step "Use the latest commit that contains the invoicey.app code defaults."
step "If that commit is not on the branch Vercel deploys, merge/push first, then redeploy."
warn "Do not Redeploy an old commit from before the trustedOrigins + URL change."
pause "Production redeploy finished?"
write_env VERCEL_REDEPLOYED 1

# ── 11. Smoke ─────────────────────────────────────────────────────────────
stage "Smoke the new host"
say "You will look signed out. That is expected (host-only cookies)."
open_url "https://invoicey.app/sign-in"
step "Google sign-in → lands on /dashboard, address bar is invoicey.app."
step "Sign out, GitHub sign-in → same."
step "Settings → Members: invite yourself on a second address if you have one."
step "From header on that mail should be @invoicey.app."
open_url "https://invoicey.app/eve/v1/health"
step "Health JSON is { ok: true, status: \"ready\" } — not marketing HTML."
step "curl -sS -X POST https://invoicey.ditrich.me/api/mcp still returns JSON (no 308)."
step "Existing ~/.invoicey/cli.json keeps working against the old apiUrl."
step "Upload an issuer logo on invoicey.app (UploadThing is same-origin)."
pause "Smoke done? Note anything that failed; we can rerun this wizard."
write_env SMOKE_OK 1

finish
note "Still later: 90-day window, then 308 leftover HTML on invoicey.ditrich.me."
note "Drive Associated Domains wait for the Apple team. Sibling invoicey-mac."
note "Existing ~/.invoicey/cli.json is not rewritten; invoicey login after the next CLI release."
