#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Do not read or write repo .env.local — that file stays Polar sandbox.
ENV_FILE="/tmp/invoicey-polar-production.env.do-not-commit"

prod_url() {
  local path="${1:-}"
  if [[ -n "${POLAR_ORG_SLUG:-}" ]]; then
    printf 'https://polar.sh/dashboard/%s%s' "$POLAR_ORG_SLUG" "$path"
  else
    printf 'https://polar.sh'
  fi
}

require_ask() {
  local key="$1" prompt="$2" val=""
  while true; do
    ask "$key" "$prompt"
    val="${!key}"
    if [[ -n "$val" ]]; then
      return 0
    fi
    warn "that value is required"
  done
}

require_ask_secret() {
  local key="$1" prompt="$2" val=""
  while true; do
    ask_secret "$key" "$prompt"
    val="${!key}"
    if [[ -n "$val" ]]; then
      return 0
    fi
    warn "that value is required"
  done
}

paste_vercel_production() {
  local key="$1" value="$2"
  open_url "https://vercel.com"
  step "Open project inveoiceyai-web → Settings → Environment Variables."
  step "Add or replace $key for Production only — not Preview, not Development."
  step "If a sandbox value is already there, overwrite it."
  note "value is in your clipboard history from the last paste into this wizard"
  warn "do not put this value in .env.local"
  pause "$key saved on Vercel Production?"
}

capture_product() {
  local key="$1" label="$2"
  say "Invoicey maps this Polar product id to $label. Prices stay in Polar."
  open_url "$(prod_url /products)"
  step "Open Products. Create or select the product described above."
  step "Copy the product id (UUID in the product URL or detail page)."
  require_ask "$key" "Paste the $label product id:"
  paste_vercel_production "$key" "${!key}"
}

banner "Invoicey Polar production"

# ── 1. Production org ─────────────────────────────────────────────────────
stage "Production org"
say "This is live Polar, not Sandbox. Tokens and product ids never cross."
open_url "https://polar.sh"
step "Stay on polar.sh. If the URL is sandbox.polar.sh, you are in the wrong place."
step "Create or open the Invoicey production organization (not the sandbox org)."
pause "Production org exists on polar.sh?"
ask POLAR_ORG_SLUG "Production org slug (from /dashboard/<slug> in the URL, or Enter to skip):"

# ── 2. Org defaults ───────────────────────────────────────────────────────
stage "Org defaults"
say "Same launch policy as sandbox: CZK default, optional EUR, no Polar benefits."
open_url "$(prod_url /settings)"
step "Open Settings and set the organization default payment currency to CZK."
step "Add EUR as an extra currency only if you want EUR checkout too."
step "Open Settings → Customer portal."
step "Turn off Enable subscription plan changes."
step "Turn off Enable subscription pause."
pause "Currency and portal toggles are set?"

# ── 3. Access token ───────────────────────────────────────────────────────
stage "Access token"
say "New production OAT. Do not reuse the sandbox token."
open_url "$(prod_url /settings)"
step "Scroll to Developers and click New Token."
step "Name it invoicey-production. Pick an expiry you are willing to rotate."
step "Enable at least: checkouts read/write and customer_sessions write."
step "Also enable products/customers/orders/subscriptions read if the list is granular."
step "Create the token and copy it now — Polar shows it once."
require_ask_secret POLAR_ACCESS_TOKEN "Paste the production organization access token:"
paste_vercel_production POLAR_ACCESS_TOKEN "$POLAR_ACCESS_TOKEN"

# ── 4–8. Products ─────────────────────────────────────────────────────────
stage "Product · Pro monthly"
say "Create a new production product. Do not paste a sandbox product id."
step "New product. Recurring interval: monthly. Price type: fixed."
step "CZK amount required. Add EUR only if you enabled EUR on the org."
step "Leave Polar benefits empty. Invoicey owns the Pro plan."
capture_product POLAR_PRODUCT_PRO_MONTHLY "Pro monthly"

stage "Product · Pro yearly"
say "Separate Polar product. Yearly recurring, same Invoicey Pro plan."
step "New product, or Duplicate Product from monthly and switch the copy to yearly before saving."
step "Recurring interval: yearly. Price type: fixed. No Polar benefits."
capture_product POLAR_PRODUCT_PRO_YEARLY "Pro yearly"

stage "Product · 2M token pack"
say "One-time fixed-price product. Invoicey credits 2,000,000 purchased tokens from the id."
step "New product. One-time purchase. Price type: fixed. No Polar benefits."
capture_product POLAR_PRODUCT_TOKENS_SMALL "2M token pack"

stage "Product · 10M token pack"
say "One-time fixed-price product. Invoicey credits 10,000,000 purchased tokens from the id."
step "New product. One-time purchase. Price type: fixed. No Polar benefits."
capture_product POLAR_PRODUCT_TOKENS_MEDIUM "10M token pack"

stage "Product · 50M token pack"
say "One-time fixed-price product. Invoicey credits 50,000,000 purchased tokens from the id."
step "New product. One-time purchase. Price type: fixed. No Polar benefits."
capture_product POLAR_PRODUCT_TOKENS_LARGE "50M token pack"

# ── 9. Production webhook ─────────────────────────────────────────────────
stage "Production webhook"
say "invoicey.app fulfills only from this production endpoint secret."
open_url "$(prod_url /settings/webhooks)"
step "Add Endpoint. URL must be exactly https://invoicey.app/api/webhooks/polar"
step "Polar does not follow redirects. Format: Raw."
step "Subscribe: order.paid, order.refunded, refund.updated,"
note "  subscription.created, subscription.updated, subscription.active,"
note "  subscription.canceled, subscription.uncanceled, subscription.past_due,"
note "  subscription.revoked, customer.created, customer.updated, customer.state_changed."
step "Copy this endpoint's signing secret — not the sandbox or polar listen secret."
require_ask_secret POLAR_WEBHOOK_SECRET "Paste the production webhook secret:"
paste_vercel_production POLAR_WEBHOOK_SECRET "$POLAR_WEBHOOK_SECRET"

# ── 10. Enable production on Vercel ───────────────────────────────────────
stage "Enable production"
say "Set POLAR_ENVIRONMENT last so a half-finished catalog cannot boot on invoicey.app."
if ! confirm "Switch Vercel Production from Polar sandbox to production?"; then
  SKIPPED+=("POLAR_ENVIRONMENT=production on Vercel Production")
  warn "left Polar environment unchanged; finish the catalog before flipping this"
else
  paste_vercel_production POLAR_ENVIRONMENT production
fi

# ── 11. Disable sandbox → invoicey.app ────────────────────────────────────
stage "Disable sandbox webhook"
say "One live URL can verify one Polar secret. Sandbox must stop posting to invoicey.app."
if ! confirm "Disable the Sandbox webhook that targets invoicey.app?"; then
  SKIPPED+=("disable sandbox webhook to https://invoicey.app/api/webhooks/polar")
  warn "sandbox events will fail signature or fight production fulfillment"
else
  open_url "https://sandbox.polar.sh"
  step "Organization switcher → Go to sandbox, then Settings → Webhooks."
  step "Find the endpoint whose URL is https://invoicey.app/api/webhooks/polar"
  step "Disable or delete that endpoint. Do not delete local polar listen."
  pause "Sandbox webhook to invoicey.app is off?"
fi

# ── 12. Redeploy and smoke ────────────────────────────────────────────────
stage "Redeploy Production"
say "Vercel must redeploy for the new Production env to load."
if confirm "Redeploy Vercel Production now?"; then
  open_url "https://vercel.com"
  step "Open project inveoiceyai-web → Deployments."
  step "Redeploy the current Production deployment (use existing build is fine)."
  pause "Production redeploy finished?"
fi
open_url "https://invoicey.app/settings/workspace/billing"
step "Sign in, open Settings → Billing."
step "Buttons should be enabled. A real card here charges real money."
step "Local laptop should still use .env.local sandbox + polar listen."
pause "invoicey.app Billing looks configured?"
# ──────────────────────────────────────────────────────────────────────────

finish
